RESOURCE_CONFIG = {
    "households": {
        "table": "households",
        "fields": ["name"],
        "required": ["name"],
        "filterable_by_household": False,
    },
    "users": {
        "table": "users",
        "fields": ["household_id", "name", "email", "role", "is_active"],
        "required": ["household_id", "name"],
        "filterable_by_household": True,
    },
    "printers": {
        "table": "printers",
        "fields": [
            "household_id",
            "name",
            "brand",
            "model",
            "nozzle_mm",
            "build_width_mm",
            "build_depth_mm",
            "build_height_mm",
            "purchase_price_cents",
            "purchase_date",
            "expected_lifetime_hours",
            "salvage_value_cents",
            "average_power_watts",
            "standby_power_watts",
            "is_active",
        ],
        "required": ["household_id", "name"],
        "filterable_by_household": True,
    },
    "materials": {
        "table": "materials",
        "fields": [
            "household_id",
            "name",
            "material_type",
            "color",
            "density_g_cm3",
            "spool_weight_g",
            "nozzle_temp_c",
            "bed_temp_c",
            "is_active",
        ],
        "required": ["household_id", "name", "material_type"],
        "filterable_by_household": True,
    },
    "material_lots": {
        "table": "material_lots",
        "fields": [
            "household_id",
            "material_id",
            "supplier_name",
            "spool_code",
            "purchased_at",
            "cost_cents",
            "gross_weight_g",
            "remaining_weight_g",
            "notes",
        ],
        "required": ["household_id", "material_id", "cost_cents"],
        "filterable_by_household": True,
    },
    "energy_rates": {
        "table": "energy_rates",
        "fields": ["household_id", "name", "price_per_kwh_cents", "effective_from", "is_active"],
        "required": ["household_id", "name", "price_per_kwh_cents"],
        "filterable_by_household": True,
    },
    "cost_settings": {
        "table": "cost_settings",
        "fields": [
            "household_id",
            "labor_rate_cents_per_hour",
            "monthly_overhead_cents",
            "default_margin_percent",
            "default_freight_subsidy_cents",
        ],
        "required": ["household_id"],
        "filterable_by_household": True,
    },
    "packaging_items": {
        "table": "packaging_items",
        "fields": ["household_id", "name", "unit", "cost_cents", "is_active"],
        "required": ["household_id", "name"],
        "filterable_by_household": True,
    },
    "sales_channels": {
        "table": "sales_channels",
        "fields": ["household_id", "name", "fee_percent", "fixed_fee_cents", "is_active"],
        "required": ["household_id", "name"],
        "filterable_by_household": True,
    },
    "products": {
        "table": "products",
        "fields": ["household_id", "sku", "name", "description", "target_margin_percent", "is_active"],
        "required": ["household_id", "name"],
        "filterable_by_household": True,
    },
    "print_jobs": {
        "table": "print_jobs",
        "fields": [
            "household_id",
            "product_id",
            "printer_id",
            "primary_material_id",
            "primary_material_lot_id",
            "requested_by_user_id",
            "status",
            "quantity",
            "estimated_print_minutes",
            "actual_print_minutes",
            "estimated_material_g",
            "actual_material_g",
            "support_material_g",
            "purge_waste_g",
            "post_process_minutes",
            "avg_power_watts",
            "failed",
            "failure_reason",
            "started_at",
            "finished_at",
            "notes",
        ],
        "required": ["household_id", "printer_id"],
        "filterable_by_household": True,
    },
    "print_job_packaging_items": {
        "table": "print_job_packaging_items",
        "fields": ["print_job_id", "packaging_item_id", "quantity", "unit_cost_cents_snapshot"],
        "required": ["print_job_id", "packaging_item_id"],
        "filterable_by_household": False,
        "touch_updated_at": False,
    },
    "orders": {
        "table": "orders",
        "fields": [
            "household_id",
            "sales_channel_id",
            "customer_name",
            "customer_reference",
            "status",
            "order_date",
            "shipping_cents",
            "discount_cents",
            "notes",
        ],
        "required": ["household_id"],
        "filterable_by_household": True,
    },
    "order_items": {
        "table": "order_items",
        "fields": ["order_id", "product_id", "print_job_id", "quantity", "selling_price_cents", "estimated_cost_cents_snapshot"],
        "required": ["order_id", "quantity", "selling_price_cents"],
        "filterable_by_household": False,
        "touch_updated_at": False,
    },
    "expenses": {
        "table": "expenses",
        "fields": ["household_id", "category", "description", "amount_cents", "occurred_on"],
        "required": ["household_id", "category", "description", "amount_cents"],
        "filterable_by_household": True,
    },
}
